# Generated by Django 5.1.1 on 2024-10-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_map_diagnosticstep_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_to_issue', to='core.issue'),
        ),
    ]
