# Generated by Django 5.1.1 on 2024-10-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_option_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticstep',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solution'),
        ),
    ]
