# Generated by Django 5.1.1 on 2024-11-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='maps', to='core.tag'),
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.mapcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mapcategory'),
        ),
    ]
