# Generated by Django 5.1.1 on 2024-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_hardware_id_customuser_license_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/issue_categories/'),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/map_categories/'),
        ),
    ]
