# Generated by Django 5.1.1 on 2024-11-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_issuecategory_logo_mapcategory_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecategory',
            name='is_car',
        ),
    ]
