# Generated by Django 5.1.1 on 2024-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_issuecategory_is_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecategory',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/issue_categories/'),
        ),
        migrations.AlterField(
            model_name='mapcategory',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/map_categories/'),
        ),
    ]
