# Generated by Django 5.1.1 on 2024-11-23 16:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_useractivity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(null=True, blank=True),  # Allowing nulls if required
        ),
    ]
