# Generated by Django 5.1.1 on 2024-11-27 23:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_customuser_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=core.models.default_start_date),
        ),
    ]
