# Generated by Django 5.1.1 on 2024-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecategory',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
