# Generated by Django 5.1.1 on 2025-01-09 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_message_is_read_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='unread_messages_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_sent',
        ),
        migrations.CreateModel(
            name='UserChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages_count', models.IntegerField(default=0)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
