# Generated by Django 5.1.1 on 2025-01-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_chatsession_unread_messages_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issuecategory'),
        ),
    ]
