# Generated by Django 5.1.1 on 2025-02-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='core.issuecategory'),
            preserve_default=False,
        ),
    ]
