# Generated by Django 5.1.1 on 2025-02-08 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_to_article', to='core.article'),
        ),
    ]
