# Generated by Django 5.1.1 on 2025-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car_brand',
            field=models.CharField(choices=[('benz', 'بنز'), ('volvo', 'ولوو'), ('scania', 'اسکانیا'), ('daf', 'داف'), ('man', 'مان'), ('renault', 'رنو'), ('foton', 'فوتون'), ('jac', 'جک'), ('iveco', 'ایویکو'), ('cummins', 'کامینز'), ('other', 'سایر')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
