# Generated by Django 5.1.1 on 2025-02-21 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_discountcode_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 21, 14, 27, 59, 244320, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
